### PR TITLE
add section on testing

### PR DESCRIPTION
**Pull request by andrewMacmurray**
subsections on: 

+ why testing
+ tdd
+ unit testing
+ end to end testing

### CODE REVIEW

**Comment by suninthesky** [comment]
Love it @andrewMacmurray! Could add something about BDD in the E2E section. And some examples of good/bad tests might be for the next version.

**Comment by andrewMacmurray** [comment]
thanks @suninthesky, good idea! Will add a bit about BDD. Maybe we could come up with some examples and show them in a couple of different languages?

**Comment by suninthesky** [comment]
Sure thing @andrewMacmurray, here's a BDD example in Ruby...
```
...
# Ruby/Rspec
scenario 'When I forget my password,
          I want to be able to reset it,
          so I access my account' do
  helper.request_reset
  expect(ActionMailer::Base.deliveries.last.subject)
    .to eq 'Reset your password - Beehive'
  expect(current_path).to eq sign_in_path
  helper.set_new_password
  expect(current_path).to eq sign_in_path
end
...
```

**Comment by andrewMacmurray** [comment]
@suninthesky brill, will add it

**Pull request merged**
